import Head from "next/head";
import { Header, Logo, Banner, Menu } from "../components";
import "react-responsive-carousel/lib/styles/carousel.min.css";

export default function Home({ products }) {
  return (
    <div className="h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo />

      <Header />
      <main className="max-w-screen-2xl mx-auto ">
        <Banner />
        <Menu products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      products,
    },
  };
}
