import Head from "next/head";
import Header from "../components/Header";
import Logo from "../components/Logo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo />

      <Header />
    </div>
  );
}
